### ISSUE TITLE
inspec-iggy doesn't works with inspec 3.0.0

### ISSUE THREAD

**Issue by ankurpshah** [inspec/inspec-iggy#18]
Try to install inspec-iggy using the following command. It fails.
```
inspec plugin install -v 0.3.0 inspec-iggy
inspec plugin install -v 0.2.0 inspec-iggy
```

Most probably inspec dependency needs to be updated for inspec 3.0.0

**Comment by mattray** [comment]
Work is being done to upgrade Iggy to a proper InSpec plugin. This will be
remediate shortly.

- Matt (mobile)
